on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - test
env:
  AZURE_WEBAPP_NAME: dotnetappGH    # set this to your application's name 
  AZURE_WEBAPP_PACKAGE_PATH: 'https://github.com/pra958/SampleDemo'      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '5.3.1' 

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      #with:
      #  vs-version: "[16.4,16.5]"  #Version of Visual Studio to search; defaults to latest if not specified

    - name: Run MSBuild
      run: msbuild .\WebApplication4.sln
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WebApplication4 }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WebApplication4/'
  
  
